In [13]:
import sqlite3
import pandas as pd

In [14]:
def load_imdb_database(db_path):
  try:
    conn = sqlite3.connect(db_path)
    print("IMDB database loaded successfully.")
    return conn
  except sqlite3.Error as e:
    print(f"Error loading IMDB database: {e}")
    return None

In [15]:
db_path = "imdb.db"
conn = load_imdb_database(db_path)

if conn:
  print("Connection successful")
  cursor = conn.cursor()

IMDB database loaded successfully.
Connection successful

In [16]:
q1 = "SELECT * FROM movie LIMIT 10"
result = pd.read_sql_query(q1, conn)
result

   index        MID                       title  year  rating  num_votes
0      0  tt2388771                      Mowgli  2018     6.6      21967
1      1  tt5164214               Ocean's Eight  2018     6.2     110861
2      2  tt1365519                 Tomb Raider  2018     6.4     142585
3      3  tt0848228                The Avengers  2012     8.1    1137529
4      4  tt8239946                     Tumbbad  2018     8.5       7483
5      5  tt7027278                   Kedarnath  2018     5.5       1970
6      6  tt3498820  Captain America: Civil War  2016     7.8     536641
7      7  tt8108198                   Andhadhun  2018     9.0      18160
8      8  tt3741834                        Lion  2016     8.1     170216
9      9  tt6747420                Rajma Chawal  2018     5.7        681

In [18]:
conn = sqlite3.connect("academic.db")
cursor = conn.cursor()

In [19]:
q2 = """CREATE TABLE students (
    id INT PRIMARY KEY,
    name VARCHAR(50),
    age INT,
    grade CHAR(1)
);"""

In [20]:
cursor.execute(q2)

OperationalError: table students already exists

In [21]:
q3 = """INSERT INTO students (id, name, age, grade)
VALUES (1, 'John Doe', 20, 'A');"""

In [22]:
cursor.execute(q3)

In [23]:
q4 = "SELECT * FROM students"
result = pd.read_sql_query(q4, conn)
result

   id      name  age grade
0   1  John Doe   20     A

In [11]:
conn.close()